move julia things here

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: CI
+name: CI with dynamic parallel matrix
 
 on:
   workflow_dispatch:
@@ -9,105 +9,91 @@ on:
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
-  cancel-in-progress: true
+  cancel-in-progress: false
 
-env:
-  NBCONVERT_JOBS: '4'
-  LITERATE_PROC: '3'
-  ALLOWERRORS: 'false'
-  CACHE_NUM: '1'
-  JULIA_CONDAPKG_BACKEND: 'Null'
-  JULIA_CI: 'true'
-  NBCACHE: '.cache'
+permissions:
+  packages: write
 
 jobs:
-  CI:
+  execute:
+    strategy:
+      fail-fast: false
+      matrix:
+        section:
+          - abm
+          - df
+          - diffeq
+          - catalyst
+          - pde
+          - ude
+          - visual
+    uses: ./.github/workflows/execute.yml
+    with:
+      dir: ${{ matrix.section }}
+
+  render:
+    needs: execute
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
-    - name: Setup Python
-      uses: actions/setup-python@v5
-      id: setup-python
-      with:
-        python-version: '3.x'
-    - name: Cache python
-      uses: actions/cache@v4
-      if: ${{ contains(runner.name, 'GitHub Actions') }}
-      id: cache-py
-      with:
-        key: ${{ runner.os }}-pip-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
-        path: |
-          ${{ env.pythonLocation }}/lib
-          ${{ env.pythonLocation }}/bin
-    - name: Install Python dependencies
-      if: ${{ !contains(runner.name, 'GitHub Actions') || steps.cache-py.outputs.cache-hit != 'true' }}
-      run: pip install -r requirements.txt
-    - name: Cache executed notebooks
-      uses: actions/cache@v4
-      id: cache-nb
-      with:
-        path: ${{ env.NBCACHE }}
-        key: ${{ runner.os }}-nb-${{ env.CACHE_NUM }}-${{ hashFiles('src/**', 'Project.toml', 'Manifest.toml') }}-${{ hashFiles('docs/**/*.ipynb', 'docs/**/*.jl') }}
-        restore-keys: |
-          ${{ runner.os }}-nb-${{ env.CACHE_NUM }}-${{ hashFiles('src/**', 'Project.toml', 'Manifest.toml') }}-
-    - name: Read Julia version
-      id: read_toml
-      run: echo "value=$(python -c 'import tomllib; from pathlib import Path; print(tomllib.loads(Path("Manifest.toml").read_text())["julia_version"])')" >> "$GITHUB_OUTPUT"
-    - name: Setup Julia
-      uses: julia-actions/setup-julia@v2
-      with:
-        version: ${{ steps.read_toml.outputs.value }}
-    - name: Restore Julia packages
-      uses: actions/cache/restore@v4
-      if: ${{ contains(runner.name, 'GitHub Actions') }}
-      id: cache-julia
-      with:
-        path: |
-          ~/.julia
-          !~/.julia/registries
-        key: ${{ runner.os }}-julia-${{ env.CACHE_NUM }}-${{ hashFiles('src/**', 'Project.toml', 'Manifest.toml') }}
-        restore-keys: |
-          ${{ runner.os }}-julia-${{ env.CACHE_NUM }}-
-    - name: Install Julia packages
-      if: ${{ !contains(runner.name, 'GitHub Actions') || steps.cache-julia.outputs.cache-hit != 'true' }}
-      env:
-        PYTHON: ${{ steps.setup-python.outputs.python-path }}
-      shell: julia --color=yes {0}
-      run: |
-        using Pkg, Dates
-        Pkg.add(["IJulia", "Literate", "PrettyTables", "JSON"])
-        Pkg.activate(".")
-        Pkg.instantiate()
-        Pkg.precompile()
-        Pkg.gc(collect_delay=Day(0))
-    - name: Save Julia packages
-      uses: actions/cache/save@v4
-      if: ${{ contains(runner.name, 'GitHub Actions') && steps.cache-julia.outputs.cache-hit != 'true' }}
-      with:
-        path: |
-          ~/.julia
-          !~/.julia/registries
-        key: ${{ steps.cache-julia.outputs.cache-primary-key }}
-    - name: Run notebooks
-      run: julia --color=yes -p ${{ env.LITERATE_PROC }} --heap-size-hint=4G run.jl
-    - name: Copy back built notebooks
-      run: cp --verbose -rf ${{ env.NBCACHE }}/docs/* docs/
-    - name: Build website
-      run: jupyter-book build docs/
-    - name: Upload pages artifact
-      if: ${{ github.ref == 'refs/heads/main' }}
-      uses: actions/upload-pages-artifact@v3
-      with:
-        path: docs/_build/html/
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Download notebooks
+        uses: actions/download-artifact@v4
+        with:
+          path: out/
+      - name: Copy back built notebooks
+        run: for d in out/notebook-*; do cp --verbose -rf "$d"/docs/* docs/; done
+      - name: Setup Python
+        uses: actions/setup-python@v5
+        id: setup-python
+        with:
+          python-version: '3.x'
+      - name: Cache python venv
+        uses: actions/cache@v4
+        if: ${{ contains(runner.name, 'GitHub Actions') }}
+        id: cache-venv
+        with:
+          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements-jb.txt') }}
+          path: .venv
+      - name: Install Python dependencies
+        run: |
+          python -m venv .venv
+          source .venv/bin/activate
+          python -m pip install -r requirements-jb.txt
+          echo "${VIRTUAL_ENV}/bin" >> $GITHUB_PATH
+          echo "VIRTUAL_ENV=${VIRTUAL_ENV}" >> $GITHUB_ENV
+      - name: Build website
+        run: jupyter-book build docs/
+      - name: Upload page artifact
+        if: ${{ github.ref == 'refs/heads/main' }}
+        uses: actions/upload-pages-artifact@v3
+        with:
+          path: docs/_build/html
 
-  # Deploy pages
+  # CI conclusion for GitHub status check
+  # Adaped from https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
+  CI:
+    needs: render
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          if [[ ${{ needs.render.result }} == "success" ]]; then
+            echo "Tests passed"
+            exit 0
+          else
+            echo "Tests failed"
+            exit 1
+          fi
+
+  # Deployment job
   deploy:
-    needs: CI
+    name: Deploy to GitHub pages
+    needs: render
     if: ${{ github.ref == 'refs/heads/main' }}
     # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
     permissions:
-      pages: write # to deploy to Pages
+      pages: write    # to deploy to Pages
       id-token: write # to verify the deployment originates from an appropriate source
       actions: read   # to download an artifact uploaded by `actions/upload-pages-artifact@v3`
     environment:
